### ISSUE TITLE
investigate rtf protocols which fail to parse

### ISSUE THREAD

**Issue by OriHoch** [hasadna/knesset-data-pipelines#24]
some rtf protocols raise exception when parsing, currently we skip them

need to investigate those errors, final goal is to allow processor to run without any exceptions which we need to skip

```
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols: INFO    :parsed parts file -> ../data/committee-meeting-protocols-parsed/5/288997.csv
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols: DEBUG   :LC_ALL=C LANG=C antiword -x db ../data/committee-meeting-protocols/5/576879.doc > ../data/committee-meeting-protocols/5/576879.doc.awdb.xml
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols: ERROR   :committee 5 meeting 576879: failed to parse doc file, skipping
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols: Traceback (most recent call last):
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:   File "/usr/local/lib/python3.6/site-packages/knesset_data/protocols/utils.py", line 36, in antiword
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:     output = subprocess.check_output(cmd,stderr=subprocess.STDOUT,shell=True)
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:   File "/usr/local/lib/python3.6/subprocess.py", line 336, in check_output
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:     **kwargs).stdout
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:   File "/usr/local/lib/python3.6/subprocess.py", line 418, in run
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:     output=stdout, stderr=stderr)
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols: subprocess.CalledProcessError: Command 'LC_ALL=C LANG=C antiword -x db ../data/committee-meeting-protocols/5/576879.doc > ../data/committee-meeting-protocols/5/576879.doc.awdb.xml' returned non-zero exit status 1.
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols: During handling of the above exception, another exception occurred:
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols: Traceback (most recent call last):
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:   File "/knesset/committees/../datapackage_pipelines_knesset/committees/processors/parse_committee_meeting_protocols.py", line 88, in _parse_doc_protocol
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:     f.write(protocol.text)
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:   File "/usr/local/lib/python3.6/site-packages/cached_property.py", line 26, in __get__
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:     value = obj.__dict__[self.func.__name__] = self.func(obj)
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:   File "/usr/local/lib/python3.6/site-packages/knesset_data/protocols/committee.py", line 53, in text
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:     text = decode(self.antiword_text, 'utf-8')
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:   File "/usr/local/lib/python3.6/site-packages/cached_property.py", line 26, in __get__
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:     value = obj.__dict__[self.func.__name__] = self.func(obj)
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:   File "/usr/local/lib/python3.6/site-packages/knesset_data/protocols/base.py", line 87, in antiword_text
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:     return antixml(self.antiword_xml)
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:   File "/usr/local/lib/python3.6/site-packages/cached_property.py", line 26, in __get__
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:     value = obj.__dict__[self.func.__name__] = self.func(obj)
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:   File "/usr/local/lib/python3.6/site-packages/knesset_data/protocols/base.py", line 83, in antiword_xml
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:     return antiword(self.file_name)
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:   File "/usr/local/lib/python3.6/site-packages/knesset_data/protocols/utils.py", line 38, in antiword
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols:     raise AntiwordException(e.returncode, e.cmd, e.output)
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols: knesset_data.protocols.exceptions.AntiwordException: 
```

**Comment by OriHoch** [comment]
handled in #15
