### ISSUE TITLE
investigate failures with committee meeting protocols pipeline

### ISSUE THREAD

**Issue by OriHoch** [hasadna/knesset-data-pipelines#49]
1. DB schema changes in committee_meeting_protocols table need to be applied (see failure in committees/all which is caused by it)

2. minio failure (probably due to long running process):
```
..datapackage_pipelines_knesset.common.processors.dump_to_sql: INFO    :committee_meeting_protocols_parsed: commit (7935 updated, 0 inserted)
..datapackage_pipelines_knesset.common.processors.dump_to_sql: INFO    :committee_meeting_protocols_parsed: commit (7985 updated, 0 inserted)
..datapackage_pipelines_knesset.common.processors.dump_to_sql: INFO    :committee_meeting_protocols_parsed: commit (8035 updated, 0 inserted)
..datapackage_pipelines_knesset.common.processors.dump_to_sql: INFO    :committee_meeting_protocols_parsed: commit (8085 updated, 0 inserted)
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols: WARNING :Connection pool is full, discarding connection: minio
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols: Traceback (most recent call last):
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:   File "/knesset/committees/../datapackage_pipelines_knesset/committees/processors/download_committee_meeting_protocols.py", line 83, in 
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:     DownloadCommitteeMeetingProtocolsProcessor.main()
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:   File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines_knesset/common/processors/base_processor.py", line 16, in main
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:     spew(*cls(*ingest()).spew())
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:   File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/wrapper/wrapper.py", line 64, in spew
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:     for rec in res:
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:   File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines_knesset/common/processors/base_processor.py", line 42, in _filter_resource
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:     yield from self._filter_row(row)
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:   File "/knesset/committees/../datapackage_pipelines_knesset/committees/processors/download_committee_meeting_protocols.py", line 72, in _filter_row
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:     if not self._save_url(meeting["url"], bucket, object_name, num_retries, seconds_between_retries):
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:   File "/knesset/committees/../datapackage_pipelines_knesset/committees/processors/download_committee_meeting_protocols.py", line 38, in _save_url
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:     object_storage.write(bucket, object_name, res.content)
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:   File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines_knesset/common/object_storage.py", line 44, in write
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:     minio.put_object(bucket, object_name, *get_write_object_data(data))
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:   File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 767, in put_object
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:     data, length, metadata=metadata)
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:   File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 1561, in _stream_put_object
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:     metadata=metadata)
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:   File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 1632, in _complete_multipart_upload
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:     content_sha256=sha256_hex)
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:   File "/usr/local/lib/python3.6/site-packages/minio/api.py", line 1781, in _url_open
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols:     object_name).get_exception()
..datapackage_pipelines_knesset.committees.processors.download_committee_meeting_protocols: minio.error.InvalidPartOrder: InvalidPartOrder: message: The list of parts was not in ascending order.Parts list must specified in order by part number.
..datapackage_pipelines_knesset.committees.processors.parse_committee_meeting_protocols: INFO    :Processed 8147 rows
..datapackage_pipelines_knesset.committees.processors.load_committee_meeting_protocols: ERROR   :Output pipe disappeared!
```

**Comment by OriHoch** [comment]
fixed
